#!/bin/bash
# generate_matrix.sh — Cross-version comparison matrix from test_results JSON archives
# Usage: bash test/generate_matrix.sh
# Output: test_results/matrix.json + test_results/matrix.md
set -euo pipefail
cd "$(dirname "$0")/.."
RESULTS="test_results"
MATRIX_JSON="$RESULTS/matrix.json"
MATRIX_MD="$RESULTS/matrix.md"

# Collect all JSON result files
declare -A VERSION_LATEST

for ver in fp64 v1.2 v1.6; do
    ver_dir="$RESULTS/$ver"
    [ -d "$ver_dir" ] || continue
    latest=$(ls -t "$ver_dir"/*.json 2>/dev/null | grep -v summary | head -1)
    [ -n "$latest" ] && VERSION_LATEST[$ver]="$latest"
done

if [ ${#VERSION_LATEST[@]} -eq 0 ]; then
    echo "No test results found. Run: bash test/run_and_record.sh <version>"
    exit 0
fi

echo "============================================================"
echo "  Cross-Version Comparison Matrix"
echo "============================================================"
echo ""

# ====== JSON Matrix ======
echo "{" > "$MATRIX_JSON"
echo '  "generated": "'$(date -Iseconds)'",' >> "$MATRIX_JSON"
echo '  "versions": {' >> "$MATRIX_JSON"

for ver in "${!VERSION_LATEST[@]}"; do
    f="${VERSION_LATEST[$ver]}"
    summary=$(jq '{run_id, version, git_commit, summary, coverage}' "$f" 2>/dev/null)
    echo "    \"$ver\": $summary," >> "$MATRIX_JSON"
done
sed -i '$ s/,$//' "$MATRIX_JSON"  # remove trailing comma
echo '  }' >> "$MATRIX_JSON"
echo '}' >> "$MATRIX_JSON"

# ====== Markdown Matrix ======
cat > "$MATRIX_MD" << 'MDEOF'
# Cross-Version Comparison Matrix

> Auto-generated by `test/generate_matrix.sh` on $(date)

## NaN Summary

| Circuit | fp64 | v1.2 | v1.6 |
|---------|:--:|:--:|:--:|
MDEOF

# Extract NaN counts per circuit per version
declare -A NAN_MAP
CIRCUITS=()

for ver in "${!VERSION_LATEST[@]}"; do
    f="${VERSION_LATEST[$ver]}"
    while IFS= read -r circuit; do
        CIRCUITS+=("$circuit")
        nan=$(jq -r ".circuits[\"$circuit\"].nan_count // \"?\"" "$f" 2>/dev/null)
        NAN_MAP["${ver}|${circuit}"]="$nan"
    done < <(jq -r '.circuits | keys[]' "$f" 2>/dev/null)
done

# Deduplicate circuit names
CIRCUITS=($(printf '%s\n' "${CIRCUITS[@]}" | sort -u))

for circuit in "${CIRCUITS[@]}"; do
    printf "| %-25s" "$circuit" >> "$MATRIX_MD"
    for ver in fp64 v1.2 v1.6; do
        nan="${NAN_MAP["${ver}|${circuit}"]:-?}"
        if [ "$nan" = "0" ]; then
            printf " | ✅" >> "$MATRIX_MD"
        elif [ "$nan" = "?" ]; then
            printf " | —" >> "$MATRIX_MD"
        else
            printf " | ❌ %s" "$nan" >> "$MATRIX_MD"
        fi
    done
    echo "" >> "$MATRIX_MD"
done

cat >> "$MATRIX_MD" << 'MDEOF'

## Coverage Comparison

| Metric | fp64 | v1.2 | v1.6 |
|--------|:--:|:--:|:--:|
MDEOF

for ver in fp64 v1.2 v1.6; do
    f="${VERSION_LATEST[$ver]:-}"
    [ -z "$f" ] && continue
    total=$(jq '.summary.total // "?"' "$f" 2>/dev/null)
    passed=$(jq '.summary.passed // "?"' "$f" 2>/dev/null)
    pct=$(jq -r "if .summary.total > 0 then (.summary.passed / .summary.total * 100 | floor) else \"?\" end" "$f" 2>/dev/null)
    echo "| Pass Rate | $passed/$total (${pct}%) |" >> "$MATRIX_MD"
done

echo "" >> "$MATRIX_MD"
echo "## Issue Tracker" >> "$MATRIX_MD"
echo "" >> "$MATRIX_MD"
echo "| Circuit | Version | NaN | Root Cause | Status |" >> "$MATRIX_MD"
echo "|---------|---------|:---:|------------|:------:|" >> "$MATRIX_MD"

# Auto-populate known issues from NaN>0 entries
for ver in "${!VERSION_LATEST[@]}"; do
    f="${VERSION_LATEST[$ver]}"
    jq -r '.circuits | to_entries[] | select(.value.nan_count > 0) | "| \(.key) | '"$ver"' | \(.value.nan_count) | TBD | 🔴 open |"' "$f" 2>/dev/null
done >> "$MATRIX_MD"

echo "" >> "$MATRIX_MD"
echo "*Generated: $(date)*" >> "$MATRIX_MD"

echo "  Matrix JSON: $MATRIX_JSON"
echo "  Matrix MD:   $MATRIX_MD"
echo "Done."
