#!/usr/bin/env python3
"""Generate pure-FP32 patches from mixed-precision originals.

Transforms patches 003, 004 by converting double-precision island blocks
to use float instead of double. All other patches are copied verbatim.
Patches 012, 013, 015 are excluded (they exclusively add double casts).

Transformation rules:
  1. In blocks delimited by "DOUBLE PRECISION ISLAND" comments or
     containing double d_* variables holding float-casted inputs:
     - double d_*  ->  float f_*
     - (double)    ->  (float)  (only within island blocks)
  2. All other content is preserved unchanged.
"""

import os
import re
import shutil

SRC_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "patches")
DST_DIR = os.path.join(SRC_DIR, "pure_fp32")

# Patches to copy verbatim
COPY_PATCHES = [
    "001-typedefs-spice-macros.patch",
    "002-bsim4v5def-struct-fp32.patch",
    "005-b4v5set-spice-real.patch",
    "006-b4v5noi-fp32.patch",
    "007-b4v5pzld-fp32.patch",
    "008-b4v5acld-fp32.patch",
    "009-b4v5geo-fp32.patch",
    "010-devsup-spice-real.patch",
    "011-spconfig-include.patch",
    "014-cmin-sollim-solver.patch",
]

# Patches to transform (remove double islands)
TRANSFORM_PATCHES = {
    "003-b4v5ld-hotpath-fp32.patch": "003-b4v5ld-pure-fp32.patch",
    "004-b4v5temp-double-island.patch": "004-b4v5temp-pure-fp32.patch",
}

# Patches to skip entirely (pure double-cast additions)
SKIP_PATCHES = [
    "012-b4v5temp-vbi-overflow-fix.patch",
    "013-multi-t-nan-fix.patch",
    "015-noise-fp64-island.patch",
]


def is_island_block_line(line):
    """Check if a line is inside a double-precision island block."""
    return bool(re.search(r'DOUBLE PRECISION ISLAND|double d_\w+\s*=', line))


def transform_patch(content):
    """Transform a patch by converting double islands to float islands.

    Strategy: in '+' lines (patch additions), convert all 'double' local
    variables to 'float'. This removes the precision safety net from the
    double-precision island blocks, making them float islands.

    We do NOT convert '-' lines (they show vanilla code being removed).
    We do NOT convert 'float f_' lines (they're already FP32 blocks).
    """
    lines = content.split('\n')
    result = []

    for line in lines:
        # Only transform '+' lines (patch additions)
        if line.startswith('+'):
            # Convert 'double d_xxx' -> 'float f_xxx' (island variables)
            line = re.sub(r'\bdouble\s+(d\w+)', r'float \1', line)
            line = re.sub(r'\bconst\s+double\s+(d\w+)', r'const float \1', line)
            # Convert (double) casts
            line = line.replace('(double)', '(float)')
            # Update comments
            line = line.replace('DOUBLE PRECISION ISLAND',
                                'PURE FP32 (no double promotion)')
            line = line.replace('FP32-NAN:', 'FP32-NAN(pure):')
            line = line.replace('FP32-INF:', 'FP32-INF(pure):')
            line = line.replace('FP32-ZERO:', 'FP32-ZERO(pure):')

        result.append(line)

    return '\n'.join(result)


def main():
    # Clean and recreate destination
    if os.path.exists(DST_DIR):
        shutil.rmtree(DST_DIR)
    os.makedirs(DST_DIR)

    # Copy unchanged patches
    for patch_name in COPY_PATCHES:
        src = os.path.join(SRC_DIR, patch_name)
        dst = os.path.join(DST_DIR, patch_name)
        if os.path.exists(src):
            shutil.copy2(src, dst)
            print(f"  COPY: {patch_name}")
        else:
            print(f"  MISSING: {patch_name} — skipping")

    # Transform patches
    for src_name, dst_name in TRANSFORM_PATCHES.items():
        src = os.path.join(SRC_DIR, src_name)
        dst = os.path.join(DST_DIR, dst_name)
        if not os.path.exists(src):
            print(f"  MISSING: {src_name} — skipping")
            continue

        with open(src, 'r', encoding='utf-8', errors='replace') as f:
            content = f.read()

        transformed = transform_patch(content)

        with open(dst, 'w', encoding='utf-8') as f:
            f.write(transformed)

        # Count transformations
        orig_double_count = content.count('double d')
        new_float_count = transformed.count('float f')
        print(f"  XFORM: {src_name} -> {dst_name} "
              f"({orig_double_count} double-d -> {new_float_count} float-f islands)")

    # List skipped patches
    for patch_name in SKIP_PATCHES:
        src = os.path.join(SRC_DIR, patch_name)
        exists = "EXISTS" if os.path.exists(src) else "MISSING"
        print(f"  SKIP: {patch_name} ({exists} — pure double-cast, not needed for Pure FP32)")

    # Write NOTES.md
    notes_path = os.path.join(DST_DIR, "NOTES.md")
    with open(notes_path, 'w') as f:
        f.write("""# Pure FP32 Patch Set

Generated by `scripts/gen_pure_fp32_patches.py` from the main `patches/` directory.

## Purpose

These patches produce a **Pure FP32** (all-float, no double-precision islands) build of ngspice-46.
This serves as the "strawman" control group in the 3-way ablation study:

| Build | Patches | SPICE_REAL | Math | Islands |
|-------|---------|------------|------|---------|
| FP64  | All 15 (no-ops) | double | exp(), sqrt() | N/A |
| Mixed FP32 | All 15 | float | expf(), sqrtf() | double-precision islands active |
| **Pure FP32** | **10 patches** | **float** | **expf(), sqrtf()** | **none** |

## Included Patches (10)

""")
        for p in COPY_PATCHES:
            f.write(f"- `{p}`\n")
        for _, dst_name in TRANSFORM_PATCHES.items():
            f.write(f"- `{dst_name}` (transformed from original, double islands removed)\n")

        f.write("""
## Excluded Patches (5)

These patches exclusively add double-precision safety nets. They are excluded
because Pure FP32 intentionally lets these overflow/underflow to demonstrate
the failure modes:

""")
        for p in SKIP_PATCHES:
            f.write(f"- `{p}`\n")

        f.write("""
## Transformation Details

The `transform_patch()` function in `gen_pure_fp32_patches.py`:
1. Finds blocks delimited by `/* DOUBLE PRECISION ISLAND */` comments
2. Converts `double d_*` variable declarations to `float f_*`
3. Converts `(double)` casts to `(float)`
4. The FP32 math blocks (Vth, Vgsteff, Weff, Rds, Vdsat, Vdseff, Idl, VADIBL,
   VASCBE, Source Velocity Limit) already use `float f_*` and are preserved as-is.

## Expected Behavior

- DC: Works for basic circuits (single NMOS/PMOS), but with larger errors than Mixed FP32
- Vbi: May produce Inf for PTM 45nm (nsd*ndep/ni^2 > FLT_MAX)
- Noise: Flicker noise produces NaN (oxideTrapDensity > FLT_MAX)
- Non-TT corners: Earlier convergence failure than Mixed FP32
""")

    print(f"\nDone! Pure FP32 patches in: {DST_DIR}")
    print(f"Total: {len(COPY_PATCHES) + len(TRANSFORM_PATCHES)} patches")


if __name__ == "__main__":
    main()
